### ISSUE TITLE
Setup auto-merge for npm patch releases

### ISSUE THREAD

**Issue by Mopolo** [Mopolo/mopolo.github.io#68]
- [x] Add a workflow to run Psalm and `npm build` in PRs
- [x] Add a workflow to auto-merge Dependabot PRs for patch releases in npm.

```yml
name: Dependabot auto-merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.1.1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Enable auto-merge for Dependabot PRs
        if: ${{steps.metadata.outputs.package-ecosystem == 'npm' && steps.metadata.outputs.update-type == 'version-update:semver-patch'}}
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

```
